[package]
name = "_"
version = "0.0.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
chrono-tz = "0.6.1"
csscolorparser = { version = "0.6.0", features = ["serde"] }
maud = "0.23.0"
ndarray = "0.15.4"
pulldown-cmark = "0.9.1"
rrule = "0.8.0"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
serde_yaml = "0.8.24"

[dev-dependencies]
cargo-make = "0.36.0"
cargo-watch = "8.1.1"
live-server = "0.4.1"
markdown-toc = "0.2.0"
sd = "0.7.6"
