[workspace]

[package]
name = "_"
version = "0.0.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
chrono-tz = "0.6.1"
console-subscriber = "0.1.8"
const_env = "0.1.2"
csscolorparser = { version = "0.6.0", features = ["serde"] }
futures = "0.3.24"
maud = "0.24.0"
ndarray = "0.15.4"
once_cell = "1.16.0"
rrule = "0.10.0"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
serde_yaml = "0.9.11"
ssg = { version = "0.0.0", path = "ssg" }
# TODO less features
tokio = { version = "1.21.0", features = ["fs", "tokio-macros", "full"] }
tokio-stream = { version = "0.1.9", features = ["fs", "sync"] }
url = "2.3.1"

[dev-dependencies]
cargo-make = "0.36.0"
cargo-watch = "8.1.1"
live-server = "0.5.0"
markdown-toc = "0.2.0"
sd = "0.7.6"
