[package]
name = "_"
version = "0.0.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.19", features = ["serde"] }
chrono-tz = "0.6.1"
const_env = "0.1.2"
counted-array = "0.1.2"
csscolorparser = { version = "0.6.0", features = ["serde"] }
hex-literal = "0.3.4"
maud = "0.23.0"
michie = "1.1.0"
ndarray = "0.15.4"
pulldown-cmark = "0.9.1"
readext = "0.1.0"
reqwest = { version = "0.11.11", features = ["blocking"] }
rrule = "0.10.0"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
serde_yaml = "0.9.11"
sha2 = "0.10.5"
zip = "0.6.2"

[dev-dependencies]
cargo-make = "0.36.0"
cargo-watch = "8.1.1"
live-server = "0.5.0"
markdown-toc = "0.2.0"
sd = "0.7.6"
