[env]
CARGO_TERM_COLOR = "always"

[tasks.pre-commit]
command = "./git_hooks/pre-commit"

[tasks.ci]
run_task = { name = ["pre-commit", "produce_output"], parallel = true }

[tasks.table_of_contents]
script = '''
#!/usr/bin/env bash
set -euxo pipefail
toc=$(cargo bin md-toc --header "# Table of contents" README.md)
MARKER='<!-- TOC -->'
cargo bin sd "$MARKER[\S\s]*$MARKER" $"$MARKER$toc\n$MARKER" README.md
'''

[tasks.produce_output]
script = '''
#!/usr/bin/env bash
set -euxo pipefail
cargo run
'''

[tasks.watch]
script = '''
#!/usr/bin/env bash
set -euxo pipefail
cargo bin cargo-watch --shell 'cargo bin cargo-make produce_output'
'''

[tasks.serve]
dependencies = ["produce_output"]
script = '''
#!/usr/bin/env bash
set -euxo pipefail
cargo bin live-server --host localhost ${OUTPUT_DIR}
'''

[tasks.dev]
run_task = { name = ["watch", "serve"], parallel = true }
