[env]
CARGO_TERM_COLOR = "always"

[tasks.watch]
script = '''
#!/usr/bin/env bash
set -euxo pipefail
cargo bin cargo-watch --exec run
'''

[tasks.serve]
script = '''
#!/usr/bin/env bash
set -euxo pipefail
cargo run
cargo bin live-server --host localhost ${OUTPUT_DIR}
'''

[tasks.dev]
run_task = { name = ["watch", "serve"], parallel = true }
