[env]
CARGO_TERM_COLOR = "always"

[tasks.produce_output]
script = '''
#!/usr/bin/env bash
set -euxo pipefail
cargo run
'''

[tasks.watch]
script = '''
#!/usr/bin/env bash
set -euxo pipefail
cargo bin cargo-watch --shell 'cargo bin cargo-make produce_output'
'''

[tasks.serve]
dependencies = ["produce_output"]
script = '''
#!/usr/bin/env bash
set -euxo pipefail
cargo bin live-server --host localhost ${OUTPUT_DIR}
'''

[tasks.dev]
run_task = { name = ["watch", "serve"], parallel = true }
