on: [push, pull_request]
permissions:
  contents: write
  pull-requests: write
env:
  RUST_BACKTRACE: 1
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - uses: actions/cache@v3
        with:
          path: |
            .bin/
            target/
            ~/.cargo/
          key: ${{ runner.os }}_cargo-run-bin_${{ hashFiles('rust-toolchain.toml', 'Cargo.toml', 'Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}_cargo-run-bin_
            ${{ runner.os }}_
      - run: cargo install cargo-run-bin
      - run: npm ci
      - run: ./git_hooks/pre-commit
      - run: cargo run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: no_untracked
        run: |
          set -euxo pipefail
          if [[ `git ls-files --exclude-standard --others` ]]; then
            echo "untracked files detected"
            exit 1
          fi
      - name: no_modified
        run: |
          set -euxo pipefail
          if ! git diff --exit-code; then
            echo "modified files detected"
            exit 1
          fi
      - id: deploy
        if: github.event_name == 'pull_request'
        run: |
          npx vercel pull --yes --environment=preview --scope mobusoperandi --token=${{ secrets.VERCEL_TOKEN }}
          URL=$(npx vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "URL=$URL" >> $GITHUB_OUTPUT
      - if: github.event_name == 'pull_request'
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Branch deployed for review at:
            ${{ steps.deploy.outputs.URL }}
      - id: get_output_dir
        run: echo "OUTPUT_DIR=$(cargo run -- print-output-dir)" >> $GITHUB_OUTPUT
      - uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          folder: ${{ steps.get_output_dir.outputs.OUTPUT_DIR }}
