on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cargo install cargo-run-bin
          cargo bin makers ci
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
