on: push
permissions:
  contents: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rustup update
      - uses: actions/cache@v3
        with:
          path: |
            .bin/
            target/
            ~/.cargo/
          key: ${{ hashFiles('Cargo.toml', 'Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}_cargo-run-bin_
            ${{ runner.os }}_
      - run: cargo install cargo-run-bin
      - run: npm ci
      - run: source constants.sh && cargo bin cargo-make ci
      - uses: JamesIves/github-pages-deploy-action@v4
        if: github.ref == 'refs/heads/master'
        with:
          folder: output
