on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          npm ci
          npm run lint
          npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
